[information]
 name = "zen"
 background = "dark"
 author = 'Sajan'

[palette]
  fg = "#FFFFFF"
  bg = "#000000"
  sfg = "#969696"
  orange1 = "#DB8530"
  orange2 = "#D6492E"
  purple = "#6A42F6"
  green = "#39ED2A"
  red = "#E60000"
  blue = "#569CD6"
  visualline = "#264F78"
  cursor_fg = "#000000"
  cursor_bg = "#9D9D9D"

[highlights]
 Normal = 'fg bg'
 SignColumn = '- bg'
 MsgArea = 'fg bg'
 ModeMsg = 'fg bg'
 MsgSeparator = 'fg bg'
 # SpellBad = 'light_red - u'
 # SpellCap = 'yellow - u'
 # SpellLocal = 'green - u'
 # SpellRare = 'purple - u'
 NormalNC = 'fg bg'
 Pmenu = 'fg bg - - 50'
 PmenuSel = 'bg fg'
 # WildMenu = 'fg ui2_blue'
 CursorLineNr = 'fg -'
 LineNrAbove = 'sfg -'
 LineNrBelow = 'sfg -'
 Comment = 'sfg -'
 # Folded = 'accent alt_bg'
 # FoldColumn = 'accent alt_bg'
 # LineNr = 'gray -'
 # FloatBorder = 'gray alt_bg'
 Whitespace = 'bg -'
 # VertSplit = 'gray bg'
 CursorLine = '- bg'
 CursorColumn = '- bg'
 ColorColumn = '- bg'
 NormalFloat = '- bg'
 Visual = '- visualline'
 # VisualNOS = '- alt_bg'
 WarningMsg = 'red bg'
 # DiffAdd = 'bg cyan'
 # DiffChange = 'bg sign_change u'
 # DiffDelete = 'alt_bg sign_delete'
 # QuickFixLine = '- ui2_blue'
 # PmenuSbar = '- alt_bg'
 # PmenuThumb = '- gray'
 # MatchWord = '- - u'
 # MatchParen = 'hint_blue bg u'
 # MatchWordCur = '- - u'
 # MatchParenCur = '- - u'
 Cursor = 'cursor_fg cursor_bg'
 lCursor = 'cursor_fg cursor_bg'
 CursorIM = 'cursor_fg cursor_bg'
 TermCursor = 'cursor_fg cursor_bg'
 TermCursorNC = 'cursor_fg cursor_bg'
 # Conceal = 'accent'
 # Directory = 'blue'
 # SpecialKey = 'blue - b'
 Title = 'fg - b'
 # ErrorMsg = 'error_red bg b'
 # Search = 'light_gray search_blue'
 # IncSearch = 'search_orange light_gray'
 # Substitute = 'light_gray search_orange'
 # MoreMsg = 'orange'
 # Question = 'orange'
 EndOfBuffer = 'purple'
 # NonText = 'bg'
 Variable = 'fg'
 Constant = 'fg'
 String = 'fg'
 Character = 'fg'
 Number = 'fg'
 Boolean = 'fg'
 Float = 'fg'
 Identifier = 'fg'
 Function = 'fg'
 Operator = 'fg'
 Type = 'fg'
 StorageClass = 'fg'
 Structure = 'fg'
 Typedef = 'fg'
 Keyword = 'fg'
 Statement = 'fg'
 Conditional = 'fg'
 Repeat = 'fg'
 Label = 'fg'
 Exception = 'fg'
 Include = 'fg'
 PreProc = 'fg'
 Define = 'fg'
 Macro = 'fg'
 PreCondit = 'fg'
 Special = 'fg'
 SpecialChar = 'fg'
 Tag = 'fg'
 # Debug = 'red'
 # Delimiter = 'gray -'
 # SpecialComment = 'gray'
 # Underlined = '- - u'
 Bold = '- - b'
 Italic = '- - i'
 Ignore = 'fg bg'
 Todo = 'fg bg'
 Error = 'red bg'
 # TabLine = 'light_gray line'
 # TabLineSel = 'white line'
 # TabLineFill = 'line line'

[Treesitter]
 TSComment = 'link:Comment'
 TSAnnotation = 'fg'
 TSAttribute = 'fg'
 TSConstructor = 'fg'
 TSType = 'fg'
 TSTypeBuiltin = 'fg'
 TSConditional = 'fg'
 TSException = 'fg'
 TSInclude = 'fg'
 TSKeywordReturn = 'fg'
 TSKeyword = 'fg'
 TSKeywordFunction = 'fg'
 TSLabel = 'fg'
 TSNamespace = 'fg'
 TSRepeat = 'fg'
 TSConstant = 'fg'
 TSConstBuiltin = 'fg'
 TSFloat = 'fg'
 TSNumber = 'fg'
 TSBoolean = 'fg'
 TSCharacter = 'fg'
 TSError = 'red'
 TSFunction = 'fg'
 TSFuncBuiltin = 'fg'
 TSMethod = 'fg'
 TSConstMacro = 'fg'
 TSFuncMacro = 'fg'
 TSVariable = 'fg'
 TSVariableBuiltin = 'red'
 TSProperty = 'red'
 TSField = 'fg'
 TSParameter = 'red'
 TSParameterReference = 'red'
 TSSymbol = 'fg'
 TSText = 'fg'
 TSOperator = 'fg'
 TSPunctDelimiter = 'fg -'
 TSTagDelimiter = 'fg'
 TSTagAttribute = 'fg'
 TSPunctBracket = 'fg -'
 TSPunctSpecial = 'fg'
 TSString = 'fg'
 TSStringRegex = 'fg'
 TSStringEscape = 'fg'
 TSTag = 'fg'
 TSEmphasis = '- - i'
 TSUnderline = '- - u'
 TSTitle = 'fg - -'
 TSLiteral = 'fg'
 TSURI = 'fg - u'
 TSKeywordOperator = 'fg'
 TSStructure = 'fg'
 TSStrong = 'fg - b'
 TSQueryLinterError = 'fg'
 TreesitterContext = '- bg'

[markdown]
 markdownBlockquote = 'fg'
 markdownCode = 'fg'
 markdownCodeBlock = 'fg'
 markdownCodeDelimiter = 'fg'
 markdownH1 = 'fg'
 markdownH2 = 'fg'
 markdownH3 = 'fg'
 markdownH4 = 'fg'
 markdownH5 = 'fg'
 markdownH6 = 'fg'
 markdownHeadingDelimiter = 'fg'
 markdownHeadingRule = 'fg - b'
 markdownId = 'fg'
 markdownIdDeclaration = 'fg'
 markdownIdDelimiter = 'fg'
 markdownLinkDelimiter = 'fg'
 markdownBold = 'fg - b'
 markdownItalic = '- - i'
 markdownBoldItalic = 'fg - bi'
 markdownListMarker = 'fg'
 markdownOrderedListMarker = 'fg'
 markdownRule = 'red'
 markdownUrl = 'fg - u'
 markdownLinkText = 'fg'
 markdownFootnote = 'fg'
 markdownFootnoteDefinition = 'fg'
 markdownEscape = 'red'

[Git]
 SignAdd = 'fg'
 SignChange = 'fg'
 SignDelete = 'red'
 GitSignsAdd = 'green1'
 GitSignsChange = 'orange1'
 GitSignsDelete = 'red'

[LSP]
 LspDiagnosticsDefaultError = 'red'
 LspDiagnosticsDefaultWarning = 'orange2'
 LspDiagnosticsDefaultInformation = 'fg'
 LspDiagnosticsDefaultInfo = 'fg'
 LspDiagnosticsDefaultHint = 'fg'
 LspDiagnosticsVirtualTextError = 'red'
 LspDiagnosticsVirtualTextWarning = 'orange2'
 LspDiagnosticsVirtualTextInformation = 'fg'
 LspDiagnosticsVirtualTextInfo = 'fg'
 LspDiagnosticsVirtualTextHint = 'fg'
 LspDiagnosticsFloatingError = 'red'
 LspDiagnosticsFloatingWarning = 'orange2'
 LspDiagnosticsFloatingInformation = 'fg'
 LspDiagnosticsFloatingInfo = 'fg'
 LspDiagnosticsFloatingHint = 'fg'
 DiagnosticSignError = 'red'
 DiagnosticSignWarning = 'orange2'
 DiagnosticSignInformation = 'fg'
 DiagnosticSignInfo = 'fg'
 DiagnosticSignHint = 'fg'
 LspDiagnosticsSignError = 'red'
 LspDiagnosticsSignWarning = 'orange2'
 LspDiagnosticsSignInformation = 'fg'
 LspDiagnosticsSignInfo = 'fg'
 LspDiagnosticsSignHint = 'fg'
 LspDiagnosticsError = 'red'
 LspDiagnosticsWarning = 'orange2'
 LspDiagnosticsInformation = 'fg'
 LspDiagnosticsInfo = 'fg'
 LspDiagnosticsHint = 'fg'
 LspDiagnosticsUnderlineError = '- - u'
 LspDiagnosticsUnderlineWarning = '- - u'
 LspDiagnosticsUnderlineInformation = '- - u'
 LspDiagnosticsUnderlineInfo = '- - u'
 LspDiagnosticsUnderlineHint = '- - u'
 LspReferenceRead = '- #2e303b'
 LspReferenceText = '- #2e303b'
 LspReferenceWrite = '- #2e303b'
 # LspCodeLens = 'context - i'
 # LspCodeLensSeparator = 'context - i'

[Telescope]
 TelescopeSelection = 'purple'
 TelescopeMatching = 'orange2 - b'
 TelescopeBorder = 'orange1 bg'

# [Buffer]
#  BufferCurrent = 'fg bg'
#  BufferCurrentIndex = 'fg bg'
#  BufferCurrentMod = 'info_yellow bg'
#  BufferCurrentSign = 'hint_blue bg'
#  BufferCurrentTarget = 'red bg b'

 # BufferVisible = 'fg bg'
 # BufferVisibleIndex = 'fg bg'
 # BufferVisibleMod = 'info_yellow bg'
 # BufferVisibleSign = 'gray bg'
 # BufferVisibleTarget = 'red bg b'

 # BufferInactive = 'gray alt_bg'
 # BufferInactiveIndex = 'gray alt_bg'
 # BufferInactiveMod = 'info_yellow alt_bg'
 # BufferInactiveSign = 'gray alt_bg'
 # BufferInactiveTarget = 'red alt_bg b'

[StatusLine]
 StatusLine = 'fg bg'
 StatusLineNC = 'fg bg'
 StatusLineTerm = 'link:StatusLine'
 StatusLineTermNC = 'link:StatusLineNC'
 # StatusLineSeparator = 'line'
